name: build

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["update"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Test before build tests with typescript transpiling
      # Test after build uses compiled JS in package dist folders
      - name: npm install, build, and test
        run: |
          npm install
          npm run bootstrap
          npm run lint
          npm test
          npm run build
          npm test
          npm run e2e:smoke
        env:
          CI: true
