name: build

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["update"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Test before build so we run with typescript transpiling
      # Test after clean:react make sure OK in that state too
      # Test after build uses compiled JS in package dist folders
      - name: npm install, build, and test
          npm run build:storybook
        run: |
          npm install
          npm run bootstrap
          npm run lint
          npm test
          npm run e2e:dev:smoke
          npm test
          npm run bootstrap
          npm run build:ui-components
          npm test
          npm run build:storybook
          npm run e2e:dev:smoke
          npm run build:govuk-react-jsx-next
          npm run e2e:smoke
          npm run e2e:dev:smoke
        env:
          CI: true
